// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };


type PickContentRelationshipFieldData<
	TRelationship extends prismic.CustomTypeModelFetchCustomTypeLevel1 | prismic.CustomTypeModelFetchCustomTypeLevel2 | prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<string, prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone>,
	TLang extends string
> = |
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship["id"]]:
			ContentRelationshipFieldWithData<TSubRelationship["customtypes"], TLang>;
	} &
	// Group
	{
		[TGroup in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup["id"]]:
			TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
				? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
				: never
	} &
	// Other fields
	{
		[TFieldKey in Extract<TRelationship["fields"][number], string>]:
			TFieldKey extends keyof TData ? TData[TFieldKey] : never;
	};

type ContentRelationshipFieldWithData<
	TCustomType extends readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[] | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string
> = {
	[ID in Exclude<TCustomType[number], string>["id"]]:
		prismic.ContentRelationshipField<
			ID,
			TLang,
			PickContentRelationshipFieldData<
				Extract<TCustomType[number], { id: ID }>,
				Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
				TLang
			>
		>
}[Exclude<TCustomType[number], string>["id"]];

interface GlobalNavDocumentData {}

/**
 * Global Nav document from Prismic
 *
 * - **API ID**: `global_nav`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GlobalNavDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<GlobalNavDocumentData>, "global_nav", Lang>;

type HomeDocumentDataSlicesSlice = HeroSlice | MediaHighlightSlice | ServicesShowcaseSlice

/**
 * Content for Home documents
 */
interface HomeDocumentData {
	/**
	 * Slice Zone field in *Home*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>;/**
	 * Meta Title field in *Home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: home.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;
	
	/**
	 * Meta Description field in *Home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: home.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;
	
	/**
	 * Meta Image field in *Home*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

export type AllDocumentTypes = GlobalNavDocument | HomeDocument;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * Background Media field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Link to Media
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.background_media
	 * - **Documentation**: https://prismic.io/docs/fields/link-to-media
	 */
	background_media: prismic.LinkToMediaField<prismic.FieldState, never>;
	
	/**
	 * Title field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Perform without self-abandonment
	 * - **API ID Path**: hero.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Subtitle field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Executive coaching for high-achieving leaders navigating pressure, visibility, and growth.
	 * - **API ID Path**: hero.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	subtitle: prismic.RichTextField;
	
	/**
	 * CTA Label field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Free Discovery Call
	 * - **API ID Path**: hero.default.primary.cta_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_label: prismic.KeyTextField;
	
	/**
	 * CTA Link field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Secondary Label field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: View Services
	 * - **API ID Path**: hero.default.primary.secondary_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	secondary_label: prismic.KeyTextField;
	
	/**
	 * Secondary Link field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.secondary_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	secondary_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Proof Text field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Trusted by 100+ high-achieving professionals
	 * - **API ID Path**: hero.default.primary.proof_text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	proof_text: prismic.RichTextField;
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceDefaultItem {
	/**
	 * Avatar Image field in *Hero → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.items[].avatar_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	avatar_image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<"default", Simplify<HeroSliceDefaultPrimary>, Simplify<HeroSliceDefaultItem>>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *MediaHighlight → Default → Primary*
 */
export interface MediaHighlightSliceDefaultPrimary {
	/**
	 * Label field in *MediaHighlight → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: About Us
	 * - **API ID Path**: media_highlight.default.primary.label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * Title field in *MediaHighlight → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Guiding leaders, transforming teams.
	 * - **API ID Path**: media_highlight.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Subtext field in *MediaHighlight → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.
	 * - **API ID Path**: media_highlight.default.primary.subtext
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	subtext: prismic.RichTextField;
	
	/**
	 * Media Variant field in *MediaHighlight → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: Choose a media variant
	 * - **API ID Path**: media_highlight.default.primary.media_variant
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	media_variant: prismic.SelectField<"image" | "video">;
	
	/**
	 * Image field in *MediaHighlight → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: media_highlight.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * Video Media field in *MediaHighlight → Default → Primary*
	 *
	 * - **Field Type**: Link to Media
	 * - **Placeholder**: *None*
	 * - **API ID Path**: media_highlight.default.primary.video_media
	 * - **Documentation**: https://prismic.io/docs/fields/link-to-media
	 */
	video_media: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Primary content in *MediaHighlight → Items*
 */
export interface MediaHighlightSliceDefaultItem {
	/**
	 * Stat Value field in *MediaHighlight → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 500+
	 * - **API ID Path**: media_highlight.items[].stat_value
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	stat_value: prismic.KeyTextField;
	
	/**
	 * Stat Text field in *MediaHighlight → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Statistic Title
	 * - **API ID Path**: media_highlight.items[].stat_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	stat_text: prismic.KeyTextField;
}

/**
 * Default variation for MediaHighlight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaHighlightSliceDefault = prismic.SharedSliceVariation<"default", Simplify<MediaHighlightSliceDefaultPrimary>, Simplify<MediaHighlightSliceDefaultItem>>;

/**
 * Slice variation for *MediaHighlight*
 */
type MediaHighlightSliceVariation = MediaHighlightSliceDefault

/**
 * MediaHighlight Shared Slice
 *
 * - **API ID**: `media_highlight`
 * - **Description**: Media Highlight
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaHighlightSlice = prismic.SharedSlice<"media_highlight", MediaHighlightSliceVariation>;

/**
 * Primary content in *ServicesShowcase → Default → Primary*
 */
export interface ServicesShowcaseSliceDefaultPrimary {
	/**
	 * Label field in *ServicesShowcase → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Services
	 * - **API ID Path**: services_showcase.default.primary.label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * Title field in *ServicesShowcase → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Explore our Programs
	 * - **API ID Path**: services_showcase.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Subtext field in *ServicesShowcase → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.
	 * - **API ID Path**: services_showcase.default.primary.subtext
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	subtext: prismic.RichTextField;
}

/**
 * Primary content in *ServicesShowcase → Items*
 */
export interface ServicesShowcaseSliceDefaultItem {
	/**
	 * Service Title field in *ServicesShowcase → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Executive Coaching
	 * - **API ID Path**: services_showcase.items[].service_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	service_title: prismic.KeyTextField;
	
	/**
	 * Service Text field in *ServicesShowcase → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.
	 * - **API ID Path**: services_showcase.items[].service_text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	service_text: prismic.RichTextField;
	
	/**
	 * Service Media field in *ServicesShowcase → Items*
	 *
	 * - **Field Type**: Link to Media
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_showcase.items[].service_media
	 * - **Documentation**: https://prismic.io/docs/fields/link-to-media
	 */
	service_media: prismic.LinkToMediaField<prismic.FieldState, never>;
	
	/**
	 * Button Label field in *ServicesShowcase → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Inquire Service
	 * - **API ID Path**: services_showcase.items[].button_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	button_label: prismic.KeyTextField;
	
	/**
	 * Button Link field in *ServicesShowcase → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services_showcase.items[].button_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	button_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for ServicesShowcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesShowcaseSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ServicesShowcaseSliceDefaultPrimary>, Simplify<ServicesShowcaseSliceDefaultItem>>;

/**
 * Slice variation for *ServicesShowcase*
 */
type ServicesShowcaseSliceVariation = ServicesShowcaseSliceDefault

/**
 * ServicesShowcase Shared Slice
 *
 * - **API ID**: `services_showcase`
 * - **Description**: Services Showcase
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesShowcaseSlice = prismic.SharedSlice<"services_showcase", ServicesShowcaseSliceVariation>;

declare module "@prismicio/client" {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
	}
	
	interface CreateWriteClient {
		(repositoryNameOrEndpoint: string, options: prismic.WriteClientConfig): prismic.WriteClient<AllDocumentTypes>;
	}
	
	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}
	
	namespace Content {
		export type {
			GlobalNavDocument,
			GlobalNavDocumentData,
			HomeDocument,
			HomeDocumentData,
			HomeDocumentDataSlicesSlice,
			AllDocumentTypes,
			HeroSlice,
			HeroSliceDefaultPrimary,
			HeroSliceDefaultItem,
			HeroSliceVariation,
			HeroSliceDefault,
			MediaHighlightSlice,
			MediaHighlightSliceDefaultPrimary,
			MediaHighlightSliceDefaultItem,
			MediaHighlightSliceVariation,
			MediaHighlightSliceDefault,
			ServicesShowcaseSlice,
			ServicesShowcaseSliceDefaultPrimary,
			ServicesShowcaseSliceDefaultItem,
			ServicesShowcaseSliceVariation,
			ServicesShowcaseSliceDefault
		}
	}
}
