// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Global Footer → Footer Contact Items*
 */
export interface GlobalFooterDocumentDataFooterContactItemsItem {
  /**
   * Label field in *Global Footer → Footer Contact Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Email@email.com
   * - **API ID Path**: global_footer.footer_contact_items[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Global Footer → Footer Contact Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: global_footer.footer_contact_items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Global Footer → Footer Quick Links*
 */
export interface GlobalFooterDocumentDataFooterQuickLinksItem {
  /**
   * Label field in *Global Footer → Footer Quick Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: About
   * - **API ID Path**: global_footer.footer_quick_links[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Global Footer → Footer Quick Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: global_footer.footer_quick_links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Global Footer documents
 */
interface GlobalFooterDocumentData {
  /**
   * Footer CTA Title field in *Global Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ready to elevate your career?
   * - **API ID Path**: global_footer.footer_cta_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footer_cta_title: prismic.RichTextField;

  /**
   * Footer CTA Button Label field in *Global Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Book Discovery Call
   * - **API ID Path**: global_footer.footer_cta_button_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footer_cta_button_label: prismic.KeyTextField;

  /**
   * Footer CTA Button Link field in *Global Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: global_footer.footer_cta_button_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  footer_cta_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Footer CTA Media field in *Global Footer*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: global_footer.footer_cta_media
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  footer_cta_media: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Footer Logo field in *Global Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: global_footer.footer_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  footer_logo: prismic.ImageField<never>;

  /**
   * Footer Contact Heading field in *Global Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Contact me
   * - **API ID Path**: global_footer.footer_contact_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footer_contact_heading: prismic.KeyTextField;

  /**
   * Footer Contact Items field in *Global Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: global_footer.footer_contact_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  footer_contact_items: prismic.GroupField<
    Simplify<GlobalFooterDocumentDataFooterContactItemsItem>
  >;

  /**
   * Footer Quick Links Heading field in *Global Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Quick Links
   * - **API ID Path**: global_footer.footer_quick_links_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footer_quick_links_heading: prismic.KeyTextField;

  /**
   * Footer Quick Links field in *Global Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: global_footer.footer_quick_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  footer_quick_links: prismic.GroupField<
    Simplify<GlobalFooterDocumentDataFooterQuickLinksItem>
  >;

  /**
   * Footer Copyright Text field in *Global Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: © 2026 KARINA RODRIGUEZ | All rights reserved.
   * - **API ID Path**: global_footer.footer_copyright_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footer_copyright_text: prismic.KeyTextField;
}

/**
 * Global Footer document from Prismic
 *
 * - **API ID**: `global_footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GlobalFooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GlobalFooterDocumentData>,
    "global_footer",
    Lang
  >;

/**
 * Item in *Global Nav → Navigation Links*
 */
export interface GlobalNavDocumentDataNavigationLinksItem {
  /**
   * Label field in *Global Nav → Navigation Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: About
   * - **API ID Path**: global_nav.navigation_links[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Global Nav → Navigation Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: global_nav.navigation_links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Global Nav → Social Links*
 */
export interface GlobalNavDocumentDataSocialLinksItem {
  /**
   * Platform field in *Global Nav → Social Links*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose a platform
   * - **API ID Path**: global_nav.social_links[].platform
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  platform: prismic.SelectField<
    "instagram" | "linkedin" | "tiktok" | "youtube" | "facebook" | "x"
  >;

  /**
   * Link field in *Global Nav → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: global_nav.social_links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Global Nav documents
 */
interface GlobalNavDocumentData {
  /**
   * Header Logo field in *Global Nav*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: global_nav.header_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  header_logo: prismic.ImageField<never>;

  /**
   * Header Brand Name field in *Global Nav*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Karina Rodriguez
   * - **API ID Path**: global_nav.header_brand_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  header_brand_name: prismic.KeyTextField;

  /**
   * Navigation Links field in *Global Nav*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: global_nav.navigation_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navigation_links: prismic.GroupField<
    Simplify<GlobalNavDocumentDataNavigationLinksItem>
  >;

  /**
   * Primary CTA Label field in *Global Nav*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Free Discovery Call
   * - **API ID Path**: global_nav.primary_cta_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  primary_cta_label: prismic.KeyTextField;

  /**
   * Primary CTA Link field in *Global Nav*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: global_nav.primary_cta_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Social Links field in *Global Nav*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: global_nav.social_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social_links: prismic.GroupField<
    Simplify<GlobalNavDocumentDataSocialLinksItem>
  >;
}

/**
 * Global Nav document from Prismic
 *
 * - **API ID**: `global_nav`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GlobalNavDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GlobalNavDocumentData>,
    "global_nav",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | HeroSlice
  | CenteredStatementSlice
  | EventHighlightSlice
  | FaqSlice
  | ChecklistFeatureSlice
  | ChecklistSpotlightSlice
  | MediaHighlightSlice
  | ProcessStepsSlice
  | ProfileFeatureSlice
  | RichTextContentSlice
  | TestimonialsShowcaseSlice
  | ServicesShowcaseSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>; /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type PageDocumentDataSlicesSlice =
  | HeroSlice
  | CenteredStatementSlice
  | EventHighlightSlice
  | FaqSlice
  | ChecklistFeatureSlice
  | ChecklistSpotlightSlice
  | MediaHighlightSlice
  | ProcessStepsSlice
  | ProfileFeatureSlice
  | RichTextContentSlice
  | TestimonialsShowcaseSlice
  | ServicesShowcaseSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Page Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Executive Coaching in Denver
   * - **API ID Path**: page.page_title
   * - **Tab**: Page Settings
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  page_title: prismic.KeyTextField; /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Executive Coaching in Denver | Karina Rodriguez
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes =
  | GlobalFooterDocument
  | GlobalNavDocument
  | HomeDocument
  | PageDocument;

/**
 * Primary content in *CenteredStatement → Default → Primary*
 */
export interface CenteredStatementSliceDefaultPrimary {
  /**
   * Section ID field in *CenteredStatement → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: statement
   * - **API ID Path**: centered_statement.default.primary.section_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_id: prismic.KeyTextField;

  /**
   * Theme field in *CenteredStatement → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose a theme
   * - **API ID Path**: centered_statement.default.primary.theme
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  theme: prismic.SelectField<"dark" | "light">;

  /**
   * Label field in *CenteredStatement → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow Here
   * - **API ID Path**: centered_statement.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Title field in *CenteredStatement → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Title of Section
   * - **API ID Path**: centered_statement.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Body field in *CenteredStatement → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.
   * - **API ID Path**: centered_statement.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Primary Button Label field in *CenteredStatement → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Book Discovery Call
   * - **API ID Path**: centered_statement.default.primary.primary_button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  primary_button_label: prismic.KeyTextField;

  /**
   * Primary Button Link field in *CenteredStatement → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: centered_statement.default.primary.primary_button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary Button Label field in *CenteredStatement → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Learn More
   * - **API ID Path**: centered_statement.default.primary.secondary_button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondary_button_label: prismic.KeyTextField;

  /**
   * Secondary Button Link field in *CenteredStatement → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: centered_statement.default.primary.secondary_button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondary_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Background Image field in *CenteredStatement → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: centered_statement.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for CenteredStatement Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CenteredStatementSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CenteredStatementSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CenteredStatement*
 */
type CenteredStatementSliceVariation = CenteredStatementSliceDefault;

/**
 * CenteredStatement Shared Slice
 *
 * - **API ID**: `centered_statement`
 * - **Description**: Centered Statement
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CenteredStatementSlice = prismic.SharedSlice<
  "centered_statement",
  CenteredStatementSliceVariation
>;

/**
 * Primary content in *ChecklistFeature → Default → Primary*
 */
export interface ChecklistFeatureSliceDefaultPrimary {
  /**
   * Section ID field in *ChecklistFeature → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: expertise
   * - **API ID Path**: checklist_feature.default.primary.section_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_id: prismic.KeyTextField;

  /**
   * Label field in *ChecklistFeature → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Expertise
   * - **API ID Path**: checklist_feature.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Title field in *ChecklistFeature → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Expertise built on insight & experience
   * - **API ID Path**: checklist_feature.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Image field in *ChecklistFeature → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: checklist_feature.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *ChecklistFeature → Items*
 */
export interface ChecklistFeatureSliceDefaultItem {
  /**
   * Item Text field in *ChecklistFeature → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.
   * - **API ID Path**: checklist_feature.items[].item_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  item_text: prismic.RichTextField;
}

/**
 * Default variation for ChecklistFeature Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ChecklistFeatureSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ChecklistFeatureSliceDefaultPrimary>,
  Simplify<ChecklistFeatureSliceDefaultItem>
>;

/**
 * Slice variation for *ChecklistFeature*
 */
type ChecklistFeatureSliceVariation = ChecklistFeatureSliceDefault;

/**
 * ChecklistFeature Shared Slice
 *
 * - **API ID**: `checklist_feature`
 * - **Description**: Checklist Feature
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ChecklistFeatureSlice = prismic.SharedSlice<
  "checklist_feature",
  ChecklistFeatureSliceVariation
>;

/**
 * Primary content in *ChecklistSpotlight → Default → Primary*
 */
export interface ChecklistSpotlightSliceDefaultPrimary {
  /**
   * Section ID field in *ChecklistSpotlight → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: programs
   * - **API ID Path**: checklist_spotlight.default.primary.section_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_id: prismic.KeyTextField;

  /**
   * Theme field in *ChecklistSpotlight → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose a theme
   * - **API ID Path**: checklist_spotlight.default.primary.theme
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  theme: prismic.SelectField<"dark" | "light">;

  /**
   * Image Position field in *ChecklistSpotlight → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose image position
   * - **API ID Path**: checklist_spotlight.default.primary.image_position
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  image_position: prismic.SelectField<"right" | "left">;

  /**
   * Label field in *ChecklistSpotlight → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Corporate Programs
   * - **API ID Path**: checklist_spotlight.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Title field in *ChecklistSpotlight → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: For organizations and teams building stronger leaders
   * - **API ID Path**: checklist_spotlight.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Body field in *ChecklistSpotlight → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Proven coaching and workshops for executives, managers, and teams who want sustainable performance.
   * - **API ID Path**: checklist_spotlight.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Image field in *ChecklistSpotlight → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: checklist_spotlight.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Primary Button Label field in *ChecklistSpotlight → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Inquire About Programs
   * - **API ID Path**: checklist_spotlight.default.primary.primary_button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  primary_button_label: prismic.KeyTextField;

  /**
   * Primary Button Link field in *ChecklistSpotlight → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: checklist_spotlight.default.primary.primary_button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary Button Label field in *ChecklistSpotlight → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Secondary Button
   * - **API ID Path**: checklist_spotlight.default.primary.secondary_button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondary_button_label: prismic.KeyTextField;

  /**
   * Secondary Button Link field in *ChecklistSpotlight → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: checklist_spotlight.default.primary.secondary_button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondary_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *ChecklistSpotlight → Items*
 */
export interface ChecklistSpotlightSliceDefaultItem {
  /**
   * Item Title field in *ChecklistSpotlight → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Executive Coaching
   * - **API ID Path**: checklist_spotlight.items[].item_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  item_title: prismic.KeyTextField;

  /**
   * Item Text field in *ChecklistSpotlight → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Private support for senior leaders navigating growth, complexity, and decision fatigue.
   * - **API ID Path**: checklist_spotlight.items[].item_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  item_text: prismic.KeyTextField;
}

/**
 * Default variation for ChecklistSpotlight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ChecklistSpotlightSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ChecklistSpotlightSliceDefaultPrimary>,
  Simplify<ChecklistSpotlightSliceDefaultItem>
>;

/**
 * Slice variation for *ChecklistSpotlight*
 */
type ChecklistSpotlightSliceVariation = ChecklistSpotlightSliceDefault;

/**
 * ChecklistSpotlight Shared Slice
 *
 * - **API ID**: `checklist_spotlight`
 * - **Description**: Checklist Spotlight
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ChecklistSpotlightSlice = prismic.SharedSlice<
  "checklist_spotlight",
  ChecklistSpotlightSliceVariation
>;

/**
 * Primary content in *EventHighlight → Default → Primary*
 */
export interface EventHighlightSliceDefaultPrimary {
  /**
   * Section ID field in *EventHighlight → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: next-event
   * - **API ID Path**: event_highlight.default.primary.section_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_id: prismic.KeyTextField;

  /**
   * Label field in *EventHighlight → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: In Person & Virtual
   * - **API ID Path**: event_highlight.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Title field in *EventHighlight → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Become a Great Leader
   * - **API ID Path**: event_highlight.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Body field in *EventHighlight → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Learn the tools, strategies and secrets that Karina uses to create immediate impact and inspire positive, lasting change in others.
   * - **API ID Path**: event_highlight.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Background Image field in *EventHighlight → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event_highlight.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Button Label field in *EventHighlight → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: RSVP Now
   * - **API ID Path**: event_highlight.default.primary.button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Link field in *EventHighlight → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: event_highlight.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *EventHighlight → Items*
 */
export interface EventHighlightSliceDefaultItem {
  /**
   * Detail Label field in *EventHighlight → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Date
   * - **API ID Path**: event_highlight.items[].detail_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  detail_label: prismic.KeyTextField;

  /**
   * Detail Value field in *EventHighlight → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: April 8, 2026
   * - **API ID Path**: event_highlight.items[].detail_value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  detail_value: prismic.KeyTextField;
}

/**
 * Default variation for EventHighlight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EventHighlightSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EventHighlightSliceDefaultPrimary>,
  Simplify<EventHighlightSliceDefaultItem>
>;

/**
 * Slice variation for *EventHighlight*
 */
type EventHighlightSliceVariation = EventHighlightSliceDefault;

/**
 * EventHighlight Shared Slice
 *
 * - **API ID**: `event_highlight`
 * - **Description**: Event Highlight
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EventHighlightSlice = prismic.SharedSlice<
  "event_highlight",
  EventHighlightSliceVariation
>;

/**
 * Primary content in *Faq → Default → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * Section ID field in *Faq → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: faq
   * - **API ID Path**: faq.default.primary.section_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_id: prismic.KeyTextField;

  /**
   * Theme field in *Faq → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose a theme
   * - **API ID Path**: faq.default.primary.theme
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  theme: prismic.SelectField<"light" | "dark">;

  /**
   * Label field in *Faq → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: FAQ
   * - **API ID Path**: faq.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Title field in *Faq → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Questions people often ask
   * - **API ID Path**: faq.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Intro field in *Faq → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A short introduction to the FAQ section.
   * - **API ID Path**: faq.default.primary.intro
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  intro: prismic.RichTextField;
}

/**
 * Primary content in *Faq → Items*
 */
export interface FaqSliceDefaultItem {
  /**
   * Question field in *Faq → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: What does an executive coach do?
   * - **API ID Path**: faq.items[].question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *Faq → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: An executive coach helps leaders think more clearly, navigate challenges more effectively, and grow in how they lead.
   * - **API ID Path**: faq.items[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  Simplify<FaqSliceDefaultItem>
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: FAQ
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Section ID field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: hero
   * - **API ID Path**: hero.default.primary.section_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_id: prismic.KeyTextField;

  /**
   * Background Media field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background_media
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  background_media: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Perform without self-abandonment
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Executive coaching for high-achieving leaders navigating pressure, visibility, and growth.
   * - **API ID Path**: hero.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * CTA Label field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Free Discovery Call
   * - **API ID Path**: hero.default.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_label: prismic.KeyTextField;

  /**
   * CTA Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary Label field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: View Services
   * - **API ID Path**: hero.default.primary.secondary_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondary_label: prismic.KeyTextField;

  /**
   * Secondary Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.secondary_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondary_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Proof Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Trusted by 100+ high-achieving professionals
   * - **API ID Path**: hero.default.primary.proof_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  proof_text: prismic.RichTextField;
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceDefaultItem {
  /**
   * Avatar Image field in *Hero → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].avatar_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  avatar_image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  Simplify<HeroSliceDefaultItem>
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *MediaHighlight → Default → Primary*
 */
export interface MediaHighlightSliceDefaultPrimary {
  /**
   * Section ID field in *MediaHighlight → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: about
   * - **API ID Path**: media_highlight.default.primary.section_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_id: prismic.KeyTextField;

  /**
   * Label field in *MediaHighlight → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: About Us
   * - **API ID Path**: media_highlight.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Title field in *MediaHighlight → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Guiding leaders, transforming teams.
   * - **API ID Path**: media_highlight.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtext field in *MediaHighlight → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.
   * - **API ID Path**: media_highlight.default.primary.subtext
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtext: prismic.RichTextField;

  /**
   * Media Variant field in *MediaHighlight → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose a media variant
   * - **API ID Path**: media_highlight.default.primary.media_variant
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  media_variant: prismic.SelectField<"image" | "video">;

  /**
   * Image field in *MediaHighlight → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media_highlight.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Video Media field in *MediaHighlight → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: media_highlight.default.primary.video_media
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video_media: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Primary content in *MediaHighlight → Items*
 */
export interface MediaHighlightSliceDefaultItem {
  /**
   * Stat Value field in *MediaHighlight → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 500+
   * - **API ID Path**: media_highlight.items[].stat_value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  stat_value: prismic.KeyTextField;

  /**
   * Stat Text field in *MediaHighlight → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Statistic Title
   * - **API ID Path**: media_highlight.items[].stat_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  stat_text: prismic.KeyTextField;
}

/**
 * Default variation for MediaHighlight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaHighlightSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MediaHighlightSliceDefaultPrimary>,
  Simplify<MediaHighlightSliceDefaultItem>
>;

/**
 * Slice variation for *MediaHighlight*
 */
type MediaHighlightSliceVariation = MediaHighlightSliceDefault;

/**
 * MediaHighlight Shared Slice
 *
 * - **API ID**: `media_highlight`
 * - **Description**: Media Highlight
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaHighlightSlice = prismic.SharedSlice<
  "media_highlight",
  MediaHighlightSliceVariation
>;

/**
 * Primary content in *ProcessSteps → Default → Primary*
 */
export interface ProcessStepsSliceDefaultPrimary {
  /**
   * Section ID field in *ProcessSteps → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: process
   * - **API ID Path**: process_steps.default.primary.section_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_id: prismic.KeyTextField;

  /**
   * Theme field in *ProcessSteps → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose a theme
   * - **API ID Path**: process_steps.default.primary.theme
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  theme: prismic.SelectField<"light" | "dark">;

  /**
   * Label field in *ProcessSteps → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: How It Works
   * - **API ID Path**: process_steps.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Title field in *ProcessSteps → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A simple, supportive process
   * - **API ID Path**: process_steps.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Body field in *ProcessSteps → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Use this section to explain how the work unfolds.
   * - **API ID Path**: process_steps.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *ProcessSteps → Items*
 */
export interface ProcessStepsSliceDefaultItem {
  /**
   * Step Title field in *ProcessSteps → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Discovery
   * - **API ID Path**: process_steps.items[].step_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  step_title: prismic.KeyTextField;

  /**
   * Step Text field in *ProcessSteps → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A short explanation of what happens in this step.
   * - **API ID Path**: process_steps.items[].step_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  step_text: prismic.RichTextField;
}

/**
 * Default variation for ProcessSteps Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProcessStepsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProcessStepsSliceDefaultPrimary>,
  Simplify<ProcessStepsSliceDefaultItem>
>;

/**
 * Slice variation for *ProcessSteps*
 */
type ProcessStepsSliceVariation = ProcessStepsSliceDefault;

/**
 * ProcessSteps Shared Slice
 *
 * - **API ID**: `process_steps`
 * - **Description**: Process Steps
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProcessStepsSlice = prismic.SharedSlice<
  "process_steps",
  ProcessStepsSliceVariation
>;

/**
 * Primary content in *ProfileFeature → Default → Primary*
 */
export interface ProfileFeatureSliceDefaultPrimary {
  /**
   * Section ID field in *ProfileFeature → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: about-karina
   * - **API ID Path**: profile_feature.default.primary.section_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_id: prismic.KeyTextField;

  /**
   * Label field in *ProfileFeature → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: About Me
   * - **API ID Path**: profile_feature.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Title field in *ProfileFeature → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Hi, I'm Karina Rodriguez
   * - **API ID Path**: profile_feature.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtext field in *ProfileFeature → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.
   * - **API ID Path**: profile_feature.default.primary.subtext
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtext: prismic.RichTextField;

  /**
   * Image field in *ProfileFeature → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: profile_feature.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Left Overlay Text field in *ProfileFeature → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.
   * - **API ID Path**: profile_feature.default.primary.left_overlay_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  left_overlay_text: prismic.RichTextField;

  /**
   * Right Overlay Text field in *ProfileFeature → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.
   * - **API ID Path**: profile_feature.default.primary.right_overlay_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  right_overlay_text: prismic.RichTextField;

  /**
   * Show Social Links field in *ProfileFeature → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: profile_feature.default.primary.show_social_links
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_social_links: prismic.BooleanField;
}

/**
 * Default variation for ProfileFeature Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProfileFeatureSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProfileFeatureSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProfileFeature*
 */
type ProfileFeatureSliceVariation = ProfileFeatureSliceDefault;

/**
 * ProfileFeature Shared Slice
 *
 * - **API ID**: `profile_feature`
 * - **Description**: Profile Feature
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProfileFeatureSlice = prismic.SharedSlice<
  "profile_feature",
  ProfileFeatureSliceVariation
>;

/**
 * Primary content in *RichTextContent → Default → Primary*
 */
export interface RichTextContentSliceDefaultPrimary {
  /**
   * Section ID field in *RichTextContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: content
   * - **API ID Path**: rich_text_content.default.primary.section_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_id: prismic.KeyTextField;

  /**
   * Theme field in *RichTextContent → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose a theme
   * - **API ID Path**: rich_text_content.default.primary.theme
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  theme: prismic.SelectField<"light" | "dark">;

  /**
   * Image Position field in *RichTextContent → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose an image position
   * - **API ID Path**: rich_text_content.default.primary.image_position
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  image_position: prismic.SelectField<"right" | "left">;

  /**
   * Label field in *RichTextContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow Here
   * - **API ID Path**: rich_text_content.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Title field in *RichTextContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Title of Section
   * - **API ID Path**: rich_text_content.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Body field in *RichTextContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Use this slice for longer-form page content.
   * - **API ID Path**: rich_text_content.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Image field in *RichTextContent → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text_content.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for RichTextContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichTextContent*
 */
type RichTextContentSliceVariation = RichTextContentSliceDefault;

/**
 * RichTextContent Shared Slice
 *
 * - **API ID**: `rich_text_content`
 * - **Description**: Rich Text Content
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextContentSlice = prismic.SharedSlice<
  "rich_text_content",
  RichTextContentSliceVariation
>;

/**
 * Primary content in *ServicesShowcase → Default → Primary*
 */
export interface ServicesShowcaseSliceDefaultPrimary {
  /**
   * Section ID field in *ServicesShowcase → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: services
   * - **API ID Path**: services_showcase.default.primary.section_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_id: prismic.KeyTextField;

  /**
   * Label field in *ServicesShowcase → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Services
   * - **API ID Path**: services_showcase.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Title field in *ServicesShowcase → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Explore our Programs
   * - **API ID Path**: services_showcase.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtext field in *ServicesShowcase → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.
   * - **API ID Path**: services_showcase.default.primary.subtext
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtext: prismic.RichTextField;
}

/**
 * Primary content in *ServicesShowcase → Items*
 */
export interface ServicesShowcaseSliceDefaultItem {
  /**
   * Service Title field in *ServicesShowcase → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Executive Coaching
   * - **API ID Path**: services_showcase.items[].service_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  service_title: prismic.KeyTextField;

  /**
   * Service Text field in *ServicesShowcase → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.
   * - **API ID Path**: services_showcase.items[].service_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  service_text: prismic.RichTextField;

  /**
   * Service Media field in *ServicesShowcase → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: services_showcase.items[].service_media
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  service_media: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Button Label field in *ServicesShowcase → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Inquire Service
   * - **API ID Path**: services_showcase.items[].button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Link field in *ServicesShowcase → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: services_showcase.items[].button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for ServicesShowcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesShowcaseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesShowcaseSliceDefaultPrimary>,
  Simplify<ServicesShowcaseSliceDefaultItem>
>;

/**
 * Slice variation for *ServicesShowcase*
 */
type ServicesShowcaseSliceVariation = ServicesShowcaseSliceDefault;

/**
 * ServicesShowcase Shared Slice
 *
 * - **API ID**: `services_showcase`
 * - **Description**: Services Showcase
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesShowcaseSlice = prismic.SharedSlice<
  "services_showcase",
  ServicesShowcaseSliceVariation
>;

/**
 * Primary content in *TestimonialsShowcase → Default → Primary*
 */
export interface TestimonialsShowcaseSliceDefaultPrimary {
  /**
   * Section ID field in *TestimonialsShowcase → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: testimonials
   * - **API ID Path**: testimonials_showcase.default.primary.section_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_id: prismic.KeyTextField;

  /**
   * Label field in *TestimonialsShowcase → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Testimonials
   * - **API ID Path**: testimonials_showcase.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Title field in *TestimonialsShowcase → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Changing lives, day by day.
   * - **API ID Path**: testimonials_showcase.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtext field in *TestimonialsShowcase → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.
   * - **API ID Path**: testimonials_showcase.default.primary.subtext
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtext: prismic.RichTextField;
}

/**
 * Primary content in *TestimonialsShowcase → Items*
 */
export interface TestimonialsShowcaseSliceDefaultItem {
  /**
   * Person Name field in *TestimonialsShowcase → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Name
   * - **API ID Path**: testimonials_showcase.items[].person_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  person_name: prismic.KeyTextField;

  /**
   * Person Title field in *TestimonialsShowcase → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title
   * - **API ID Path**: testimonials_showcase.items[].person_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  person_title: prismic.KeyTextField;

  /**
   * Testimonial Text field in *TestimonialsShowcase → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.
   * - **API ID Path**: testimonials_showcase.items[].testimonial_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  testimonial_text: prismic.RichTextField;

  /**
   * Media field in *TestimonialsShowcase → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_showcase.items[].media
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  media: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Default variation for TestimonialsShowcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsShowcaseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsShowcaseSliceDefaultPrimary>,
  Simplify<TestimonialsShowcaseSliceDefaultItem>
>;

/**
 * Slice variation for *TestimonialsShowcase*
 */
type TestimonialsShowcaseSliceVariation = TestimonialsShowcaseSliceDefault;

/**
 * TestimonialsShowcase Shared Slice
 *
 * - **API ID**: `testimonials_showcase`
 * - **Description**: Testimonials Showcase
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsShowcaseSlice = prismic.SharedSlice<
  "testimonials_showcase",
  TestimonialsShowcaseSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      GlobalFooterDocument,
      GlobalFooterDocumentData,
      GlobalFooterDocumentDataFooterContactItemsItem,
      GlobalFooterDocumentDataFooterQuickLinksItem,
      GlobalNavDocument,
      GlobalNavDocumentData,
      GlobalNavDocumentDataNavigationLinksItem,
      GlobalNavDocumentDataSocialLinksItem,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      CenteredStatementSlice,
      CenteredStatementSliceDefaultPrimary,
      CenteredStatementSliceVariation,
      CenteredStatementSliceDefault,
      ChecklistFeatureSlice,
      ChecklistFeatureSliceDefaultPrimary,
      ChecklistFeatureSliceDefaultItem,
      ChecklistFeatureSliceVariation,
      ChecklistFeatureSliceDefault,
      ChecklistSpotlightSlice,
      ChecklistSpotlightSliceDefaultPrimary,
      ChecklistSpotlightSliceDefaultItem,
      ChecklistSpotlightSliceVariation,
      ChecklistSpotlightSliceDefault,
      EventHighlightSlice,
      EventHighlightSliceDefaultPrimary,
      EventHighlightSliceDefaultItem,
      EventHighlightSliceVariation,
      EventHighlightSliceDefault,
      FaqSlice,
      FaqSliceDefaultPrimary,
      FaqSliceDefaultItem,
      FaqSliceVariation,
      FaqSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceDefaultItem,
      HeroSliceVariation,
      HeroSliceDefault,
      MediaHighlightSlice,
      MediaHighlightSliceDefaultPrimary,
      MediaHighlightSliceDefaultItem,
      MediaHighlightSliceVariation,
      MediaHighlightSliceDefault,
      ProcessStepsSlice,
      ProcessStepsSliceDefaultPrimary,
      ProcessStepsSliceDefaultItem,
      ProcessStepsSliceVariation,
      ProcessStepsSliceDefault,
      ProfileFeatureSlice,
      ProfileFeatureSliceDefaultPrimary,
      ProfileFeatureSliceVariation,
      ProfileFeatureSliceDefault,
      RichTextContentSlice,
      RichTextContentSliceDefaultPrimary,
      RichTextContentSliceVariation,
      RichTextContentSliceDefault,
      ServicesShowcaseSlice,
      ServicesShowcaseSliceDefaultPrimary,
      ServicesShowcaseSliceDefaultItem,
      ServicesShowcaseSliceVariation,
      ServicesShowcaseSliceDefault,
      TestimonialsShowcaseSlice,
      TestimonialsShowcaseSliceDefaultPrimary,
      TestimonialsShowcaseSliceDefaultItem,
      TestimonialsShowcaseSliceVariation,
      TestimonialsShowcaseSliceDefault,
    };
  }
}
